# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: jomia
      MONGO_INITDB_ROOT_PASSWORD: jim371def

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: jomia
      ME_CONFIG_MONGODB_ADMINPASSWORD: jim371def
      ME_CONFIG_MONGODB_URL: mongodb://jomia:jim371def@mongo:27017/